[rospy.client][INFO] 2020-12-29 04:46:50,305: init_node, name[/train_6552_1609217210277], pid[6552]
[xmlrpc][INFO] 2020-12-29 04:46:50,305: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-29 04:46:50,306: Started XML-RPC server [http://192.168.0.191:37123/]
[rospy.init][INFO] 2020-12-29 04:46:50,306: ROS Slave URI: [http://192.168.0.191:37123/]
[rospy.impl.masterslave][INFO] 2020-12-29 04:46:50,306: _ready: http://192.168.0.191:37123/
[rospy.registration][INFO] 2020-12-29 04:46:50,307: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-29 04:46:50,307: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-29 04:46:50,406: registered with master
[rospy.rosout][INFO] 2020-12-29 04:46:50,407: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-29 04:46:50,412: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-29 04:46:50,413: initializing /clock core topic
[rospy.simtime][INFO] 2020-12-29 04:46:50,416: connected to core topic /clock
[rospy.internal][INFO] 2020-12-29 04:46:50,420: topic[/clock] adding connection to [http://192.168.0.201:35809/], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,435: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:40893/], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,442: topic[/is_start_episode] adding connection to [http://192.168.0.201:43125/], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,450: topic[/scan] adding connection to [http://192.168.0.201:37455/], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,451: topic[/scan] adding connection to [http://192.168.0.201:35809/], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,456: topic[/start_goal_points] adding connection to [http://192.168.0.201:41399/], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,458: topic[/odom] adding connection to [http://192.168.0.201:35809/], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,560: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,638: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-12-29 04:46:50,639: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2020-12-29 15:32:56,715: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-12-29 15:32:56,721: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-29 15:32:56,722: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-29 15:32:56,722: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-29 15:32:56,723: topic[/clock] removing connection to http://192.168.0.201:35809/
[rospy.internal][INFO] 2020-12-29 15:32:56,724: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:40893/
[rospy.internal][INFO] 2020-12-29 15:32:56,725: topic[/odom] removing connection to http://192.168.0.201:35809/
[rospy.internal][ERROR] 2020-12-29 15:32:56,725: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 737, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 104, in recv_buff
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-12-29 15:32:56,726: Unknown error initiating TCP/IP socket to 192.168.0.201:55857 (http://192.168.0.201:40893/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-29 15:32:56,727: topic[/start_goal_points] removing connection to http://192.168.0.201:41399/
[rospy.internal][WARNING] 2020-12-29 15:32:56,727: Unknown error initiating TCP/IP socket to 192.168.0.201:39529 (http://192.168.0.201:35809/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-29 15:32:56,728: topic[/scan] removing connection to http://192.168.0.201:37455/
[rospy.internal][WARNING] 2020-12-29 15:32:56,729: Unknown error initiating TCP/IP socket to 192.168.0.201:34381 (http://192.168.0.201:41399/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-29 15:32:56,729: topic[/scan] removing connection to http://192.168.0.201:35809/
[rospy.internal][INFO] 2020-12-29 15:32:56,729: topic[/is_start_episode] removing connection to http://192.168.0.201:43125/
[rospy.impl.masterslave][INFO] 2020-12-29 15:32:56,730: signal-2
[rospy.core][INFO] 2020-12-29 15:32:57,225: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-29 15:32:57,295: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-29 15:32:57,319: signal_shutdown [atexit]
