[rospy.client][INFO] 2021-01-09 03:10:04,768: init_node, name[/train_2655_1610161804748], pid[2655]
[xmlrpc][INFO] 2021-01-09 03:10:04,769: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-09 03:10:04,769: Started XML-RPC server [http://192.168.0.162:40737/]
[rospy.impl.masterslave][INFO] 2021-01-09 03:10:04,769: _ready: http://192.168.0.162:40737/
[rospy.init][INFO] 2021-01-09 03:10:04,769: ROS Slave URI: [http://192.168.0.162:40737/]
[rospy.registration][INFO] 2021-01-09 03:10:04,769: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2021-01-09 03:10:04,770: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-09 03:10:04,869: registered with master
[rospy.rosout][INFO] 2021-01-09 03:10:04,870: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-09 03:10:04,873: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-09 03:10:04,874: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-09 03:10:04,882: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:44581/], count 0
[rospy.internal][INFO] 2021-01-09 03:10:04,891: topic[/odom] adding connection to [http://192.168.0.201:34577/], count 0
[rospy.internal][INFO] 2021-01-09 03:10:04,892: topic[/is_start_episode] adding connection to [http://192.168.0.201:45929/], count 0
[rospy.internal][INFO] 2021-01-09 03:10:04,895: topic[/scan] adding connection to [http://192.168.0.201:34577/], count 0
[rospy.internal][INFO] 2021-01-09 03:10:04,896: topic[/scan] adding connection to [http://192.168.0.201:46675/], count 0
[rospy.internal][INFO] 2021-01-09 03:10:04,897: topic[/start_goal_points] adding connection to [http://192.168.0.201:42155/], count 0
[rospy.internal][INFO] 2021-01-09 03:10:05,108: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2021-01-09 03:10:05,109: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-01-09 03:10:05,111: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2021-01-09 03:11:50,462: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-01-09 03:11:50,467: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-09 03:11:50,467: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-09 03:11:50,467: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-09 03:11:50,467: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:44581/
[rospy.internal][INFO] 2021-01-09 03:11:50,468: topic[/odom] removing connection to http://192.168.0.201:34577/
[rospy.internal][INFO] 2021-01-09 03:11:50,468: topic[/start_goal_points] removing connection to http://192.168.0.201:42155/
[rospy.internal][WARNING] 2021-01-09 03:11:50,468: Unknown error initiating TCP/IP socket to 192.168.0.201:47923 (http://192.168.0.201:34577/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2021-01-09 03:11:50,468: topic[/scan] removing connection to http://192.168.0.201:34577/
[rospy.internal][WARNING] 2021-01-09 03:11:50,469: Unknown error initiating TCP/IP socket to 192.168.0.201:46057 (http://192.168.0.201:42155/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2021-01-09 03:11:50,469: topic[/scan] removing connection to http://192.168.0.201:46675/
[rospy.internal][INFO] 2021-01-09 03:11:50,469: topic[/is_start_episode] removing connection to http://192.168.0.201:45929/
[rospy.impl.masterslave][INFO] 2021-01-09 03:11:50,469: signal-2
[rospy.internal][WARNING] 2021-01-09 03:11:50,469: Unknown error initiating TCP/IP socket to 192.168.0.201:41483 (http://192.168.0.201:46675/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2021-01-09 03:11:50,962: signal_shutdown [signal-2]
[rospy.core][INFO] 2021-01-09 03:11:50,998: signal_shutdown [signal-2]
[rospy.core][INFO] 2021-01-09 03:11:51,046: signal_shutdown [signal-2]
[rospy.core][INFO] 2021-01-09 03:11:51,065: signal_shutdown [signal-2]
[rospy.core][INFO] 2021-01-09 03:11:51,097: signal_shutdown [signal-2]
[rospy.core][INFO] 2021-01-09 03:11:51,116: signal_shutdown [signal-2]
[rospy.core][INFO] 2021-01-09 03:11:51,118: signal_shutdown [atexit]
