[rospy.client][INFO] 2021-01-18 08:29:33,666: init_node, name[/train_4288_1610958573636], pid[4288]
[xmlrpc][INFO] 2021-01-18 08:29:33,667: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-18 08:29:33,668: Started XML-RPC server [http://192.168.0.191:33891/]
[rospy.init][INFO] 2021-01-18 08:29:33,668: ROS Slave URI: [http://192.168.0.191:33891/]
[rospy.impl.masterslave][INFO] 2021-01-18 08:29:33,668: _ready: http://192.168.0.191:33891/
[rospy.registration][INFO] 2021-01-18 08:29:33,670: Registering with master node http://192.168.0.126:11311
[xmlrpc][INFO] 2021-01-18 08:29:33,670: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-18 08:29:33,769: registered with master
[rospy.rosout][INFO] 2021-01-18 08:29:33,769: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-18 08:29:33,774: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-18 08:29:33,775: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-18 08:29:33,786: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.126:34427/], count 0
[rospy.internal][INFO] 2021-01-18 08:29:33,794: topic[/odom] adding connection to [http://192.168.0.126:44411/], count 0
[rospy.internal][INFO] 2021-01-18 08:29:33,799: topic[/start_goal_points] adding connection to [http://192.168.0.126:40887/], count 0
[rospy.internal][INFO] 2021-01-18 08:29:33,805: topic[/scan] adding connection to [http://192.168.0.126:46009/], count 0
[rospy.internal][INFO] 2021-01-18 08:29:33,806: topic[/scan] adding connection to [http://192.168.0.126:44411/], count 0
[rospy.internal][INFO] 2021-01-18 08:29:33,812: topic[/is_start_episode] adding connection to [http://192.168.0.126:40755/], count 0
[rospy.internal][INFO] 2021-01-18 08:29:33,996: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-01-18 08:29:33,997: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2021-01-18 08:29:34,008: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.core][INFO] 2021-01-18 08:29:36,289: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-01-18 08:29:36,293: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-18 08:29:36,293: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-18 08:29:36,293: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-18 08:29:36,293: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.126:34427/
[rospy.internal][INFO] 2021-01-18 08:29:36,294: topic[/odom] removing connection to http://192.168.0.126:44411/
[rospy.internal][INFO] 2021-01-18 08:29:36,294: topic[/start_goal_points] removing connection to http://192.168.0.126:40887/
[rospy.internal][INFO] 2021-01-18 08:29:36,294: topic[/scan] removing connection to http://192.168.0.126:46009/
[rospy.internal][INFO] 2021-01-18 08:29:36,294: topic[/scan] removing connection to http://192.168.0.126:44411/
[rospy.internal][INFO] 2021-01-18 08:29:36,295: topic[/is_start_episode] removing connection to http://192.168.0.126:40755/
[rospy.impl.masterslave][INFO] 2021-01-18 08:29:36,295: atexit
[rospy.internal][WARNING] 2021-01-18 08:29:36,296: Unknown error initiating TCP/IP socket to 192.168.0.126:50861 (http://192.168.0.126:40755/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-18 08:29:36,296: Unknown error initiating TCP/IP socket to 192.168.0.126:43043 (http://192.168.0.126:44411/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

