[rospy.client][INFO] 2021-01-16 10:40:41,763: init_node, name[/train_3119_1610793641735], pid[3119]
[xmlrpc][INFO] 2021-01-16 10:40:41,763: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-16 10:40:41,764: Started XML-RPC server [http://192.168.0.191:40635/]
[rospy.init][INFO] 2021-01-16 10:40:41,764: ROS Slave URI: [http://192.168.0.191:40635/]
[rospy.impl.masterslave][INFO] 2021-01-16 10:40:41,764: _ready: http://192.168.0.191:40635/
[rospy.registration][INFO] 2021-01-16 10:40:41,766: Registering with master node http://192.168.0.126:11311
[xmlrpc][INFO] 2021-01-16 10:40:41,766: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-16 10:40:41,865: registered with master
[rospy.rosout][INFO] 2021-01-16 10:40:41,865: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-16 10:40:41,871: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-16 10:40:41,873: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-16 10:40:41,893: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.126:36903/], count 0
[rospy.internal][INFO] 2021-01-16 10:40:41,897: topic[/start_goal_points] adding connection to [http://192.168.0.126:40949/], count 0
[rospy.internal][INFO] 2021-01-16 10:40:41,910: topic[/scan] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 10:40:41,913: topic[/scan] adding connection to [http://192.168.0.126:36669/], count 1
[rospy.internal][INFO] 2021-01-16 10:40:41,916: topic[/is_start_episode] adding connection to [http://192.168.0.126:34007/], count 0
[rospy.internal][INFO] 2021-01-16 10:40:41,917: topic[/odom] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 10:40:42,139: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2021-01-16 10:40:42,140: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-01-16 10:40:42,141: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2021-01-16 10:40:44,443: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-01-16 10:40:44,447: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-16 10:40:44,448: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-16 10:40:44,448: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-16 10:40:44,449: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.126:36903/
[rospy.internal][INFO] 2021-01-16 10:40:44,449: topic[/odom] removing connection to http://192.168.0.126:45431/
[rospy.internal][INFO] 2021-01-16 10:40:44,450: topic[/start_goal_points] removing connection to http://192.168.0.126:40949/
[rospy.internal][INFO] 2021-01-16 10:40:44,450: topic[/scan] removing connection to http://192.168.0.126:45431/
[rospy.internal][INFO] 2021-01-16 10:40:44,451: topic[/scan] removing connection to http://192.168.0.126:36669/
[rospy.internal][WARNING] 2021-01-16 10:40:44,452: Unknown error initiating TCP/IP socket to 192.168.0.126:59449 (http://192.168.0.126:36903/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2021-01-16 10:40:44,452: topic[/is_start_episode] removing connection to http://192.168.0.126:34007/
[rospy.internal][WARNING] 2021-01-16 10:40:44,452: Unknown error initiating TCP/IP socket to 192.168.0.126:57109 (http://192.168.0.126:34007/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2021-01-16 10:40:44,453: atexit
[rospy.internal][WARNING] 2021-01-16 10:40:44,454: Unknown error initiating TCP/IP socket to 192.168.0.126:35677 (http://192.168.0.126:45431/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

