[rospy.client][INFO] 2020-12-26 05:33:38,726: init_node, name[/train_4734_1608960818698], pid[4734]
[xmlrpc][INFO] 2020-12-26 05:33:38,726: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-26 05:33:38,727: Started XML-RPC server [http://192.168.0.191:42989/]
[rospy.init][INFO] 2020-12-26 05:33:38,727: ROS Slave URI: [http://192.168.0.191:42989/]
[rospy.impl.masterslave][INFO] 2020-12-26 05:33:38,727: _ready: http://192.168.0.191:42989/
[rospy.registration][INFO] 2020-12-26 05:33:38,728: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-26 05:33:38,729: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-26 05:33:38,827: registered with master
[rospy.rosout][INFO] 2020-12-26 05:33:38,828: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-26 05:33:38,832: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-26 05:33:38,833: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-12-26 05:33:38,854: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:39549/], count 0
[rospy.internal][INFO] 2020-12-26 05:33:38,861: topic[/scan] adding connection to [http://192.168.0.201:40197/], count 0
[rospy.internal][INFO] 2020-12-26 05:33:38,863: topic[/is_start_episode] adding connection to [http://192.168.0.201:42987/], count 0
[rospy.internal][INFO] 2020-12-26 05:33:38,865: topic[/scan] adding connection to [http://192.168.0.201:37833/], count 1
[rospy.internal][INFO] 2020-12-26 05:33:38,867: topic[/start_goal_points] adding connection to [http://192.168.0.201:40835/], count 0
[rospy.internal][INFO] 2020-12-26 05:33:38,869: topic[/odom] adding connection to [http://192.168.0.201:40197/], count 0
[rospy.internal][INFO] 2020-12-26 05:33:38,998: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-26 05:33:38,999: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2020-12-26 05:33:39,097: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-12-26 05:33:46,895: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-12-26 05:33:46,902: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-26 05:33:46,902: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-26 05:33:46,902: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-26 05:33:46,903: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:39549/
[rospy.internal][INFO] 2020-12-26 05:33:46,904: topic[/odom] removing connection to http://192.168.0.201:40197/
[rospy.internal][INFO] 2020-12-26 05:33:46,904: topic[/start_goal_points] removing connection to http://192.168.0.201:40835/
[rospy.internal][INFO] 2020-12-26 05:33:46,905: topic[/scan] removing connection to http://192.168.0.201:40197/
[rospy.internal][WARNING] 2020-12-26 05:33:46,906: Unknown error initiating TCP/IP socket to 192.168.0.201:43555 (http://192.168.0.201:39549/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2020-12-26 05:33:46,906: topic[/scan] removing connection to http://192.168.0.201:37833/
[rospy.internal][INFO] 2020-12-26 05:33:46,907: topic[/is_start_episode] removing connection to http://192.168.0.201:42987/
[rospy.internal][WARNING] 2020-12-26 05:33:46,908: Unknown error initiating TCP/IP socket to 192.168.0.201:42523 (http://192.168.0.201:40835/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2020-12-26 05:33:46,908: atexit
[rospy.internal][WARNING] 2020-12-26 05:33:46,908: Unknown error initiating TCP/IP socket to 192.168.0.201:56385 (http://192.168.0.201:40197/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

