[rospy.client][INFO] 2020-12-01 09:13:39,557: init_node, name[/train_1367_1606814019529], pid[1367]
[xmlrpc][INFO] 2020-12-01 09:13:39,557: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-01 09:13:39,558: Started XML-RPC server [http://192.168.0.191:35929/]
[rospy.init][INFO] 2020-12-01 09:13:39,558: ROS Slave URI: [http://192.168.0.191:35929/]
[rospy.impl.masterslave][INFO] 2020-12-01 09:13:39,558: _ready: http://192.168.0.191:35929/
[rospy.registration][INFO] 2020-12-01 09:13:39,560: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-01 09:13:39,560: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-01 09:13:39,659: registered with master
[rospy.rosout][INFO] 2020-12-01 09:13:39,659: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-01 09:13:39,664: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-01 09:13:39,665: initializing /clock core topic
[rospy.simtime][INFO] 2020-12-01 09:13:39,668: connected to core topic /clock
[rospy.internal][INFO] 2020-12-01 09:13:39,671: topic[/clock] adding connection to [http://192.168.0.201:41281/], count 0
[rospy.internal][INFO] 2020-12-01 09:13:39,697: topic[/is_start_episode] adding connection to [http://192.168.0.201:42019/], count 0
[rospy.internal][INFO] 2020-12-01 09:13:39,698: topic[/scan] adding connection to [http://192.168.0.201:41281/], count 0
[rospy.internal][INFO] 2020-12-01 09:13:39,703: topic[/start_goal_points] adding connection to [http://192.168.0.201:41407/], count 0
[rospy.internal][INFO] 2020-12-01 09:13:39,706: topic[/odom] adding connection to [http://192.168.0.201:41281/], count 0
[rospy.internal][INFO] 2020-12-01 09:13:39,884: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-12-01 09:13:39,885: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2020-12-01 09:13:39,984: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-01 09:14:09,038: topic[/scan] adding connection to [http://192.168.0.201:37453/], count 1
[rospy.internal][INFO] 2020-12-01 09:14:09,043: topic[/bev/flow_image] adding connection to [http://192.168.0.201:34795/], count 0
[rospy.internal][INFO] 2020-12-01 09:14:09,149: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 1
[rospy.internal][WARNING] 2020-12-01 09:15:17,245: Unknown error initiating TCP/IP socket to 192.168.0.201:60501 (http://192.168.0.201:34795/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-12-01 09:15:17,246: topic[/bev/flow_image] removing connection to http://192.168.0.201:34795/
[rospy.internal][INFO] 2020-12-01 09:15:17,566: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][WARNING] 2020-12-01 09:15:18,059: Unknown error initiating TCP/IP socket to 192.168.0.201:42623 (http://192.168.0.201:37453/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-12-01 09:15:18,060: topic[/scan] removing connection to http://192.168.0.201:37453/
[rospy.core][INFO] 2020-12-01 09:15:22,088: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-12-01 09:15:22,095: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-01 09:15:22,095: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-01 09:15:22,095: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-01 09:15:22,096: topic[/clock] removing connection to http://192.168.0.201:41281/
[rospy.internal][INFO] 2020-12-01 09:15:22,096: topic[/odom] removing connection to http://192.168.0.201:41281/
[rospy.internal][INFO] 2020-12-01 09:15:22,097: topic[/start_goal_points] removing connection to http://192.168.0.201:41407/
[rospy.internal][INFO] 2020-12-01 09:15:22,097: topic[/scan] removing connection to http://192.168.0.201:41281/
[rospy.internal][WARNING] 2020-12-01 09:15:22,098: Unknown error initiating TCP/IP socket to 192.168.0.201:40113 (http://192.168.0.201:41407/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-01 09:15:22,098: topic[/is_start_episode] removing connection to http://192.168.0.201:42019/
[rospy.impl.masterslave][INFO] 2020-12-01 09:15:22,098: signal-2
[rospy.internal][WARNING] 2020-12-01 09:15:22,099: Unknown error initiating TCP/IP socket to 192.168.0.201:38151 (http://192.168.0.201:42019/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-12-01 09:15:22,589: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-01 09:15:22,619: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-01 09:15:22,651: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-01 09:15:22,683: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-01 09:15:22,692: signal_shutdown [atexit]
